version: '2.2'
services:
  # Battlefield 2 1.5 server with the bf2stats python scripts
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist (coop)
      # - ./config/bf2/mods/bf2/settings/maplist-custom-cq.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist (cq)
      - ./src/python:/server/bf2/python # Mount the python files
      - ./config/bf2/python/bf2/BF2StatisticsConfig-custom.py:/server/bf2/python/bf2/BF2StatisticsConfig.py:ro # bf2stats python config
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - bf2-network
      - gamespy-network
    depends_on:
      - asp
    tty: true
    stdin_open: true

  # The Gamespy master server
  prmasterserver:
    image: startersclan/prmasterserver:v0.1.0
    volumes:
      - prmasterserver-volume:/data
    ports:
      - 29900:29900/tcp # Login server
      - 29901:29901/tcp # Login server
      - 28910:28910/tcp # Master server
      - 27900:27900/udp # Master server
      - 29910:29910/udp # CD key server
    networks:
      # Spoof all gamespy DNS for the BF2 server connected to this network
      gamespy-network:
        aliases:
          - battlefield2.available.gamespy.com
          - battlefield2.master.gamespy.com
          - battlefield2.ms14.gamespy.com
          - master.gamespy.com
          - motd.gamespy.com
          - gpsp.gamespy.com
          - gpcm.gamespy.com
          - gamespy.com

  # The reverse proxy for our web containers
  # This is needed only for the BF2 client BFHQ to work properly (i.e. access the ASP via http://bf2web.gamespy.com)
  traefik:
    image: traefik:v2.7
    volumes:
      # Allow traefik to listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
    networks:
      - traefik-public-network
      - traefik-network
    restart: unless-stopped
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      # - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

  init-container:
    image: alpine:latest
    volumes:
      - ./src:/src
      - db-volume:/var/lib/mysql
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Granting db write permissions"
          chown -R 999:999 /var/lib/mysql

  asp:
    build:
      dockerfile: Dockerfile.asp
      context: .
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME?err}_traefik-network"
      # traefik v2
      # http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-gamespy-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-gamespy-http.rule=Host(`bf2web.gamespy.com`)" # Note: `bf2web.gamespy.com` doesn't need https. The BF2 client BFHQ makes a HTTP requests to `bf2web.gamespy.com` with `Host: bf2web.gamespy.com`.
    environment:
      # - XDEBUG_MODE=off   # Uncomment to disable xdebug
      # See ./src/ASP/system/config/config.php for all supported env vars. Use comma-delimited value for array
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=bf2stats
      - DB_USER=admin
      - DB_PASS=admin
      - ADMIN_HOSTS=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16   # Limit admins to private IPs
      - GAME_HOSTS=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16    # Limit gameservers to private IPs
      - DEBUG_LVL=2
    volumes:
      - ./src/ASP:/src/ASP
      - backups-volume:/src/ASP/system/database/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - config-volume:/src/ASP/system/config # For a stateful config file
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
    ports:
      - 8081:80
      - 9000
    networks:
      traefik-network:
      bf2-network:
        aliases:
          - bf2web.gamespy.com # Spoof gamespy DNS for the BF2 server connected to this network
    extra_hosts:
      # For xdebug to reach the host via `host.docker.internal`. See: https://github.com/moby/moby/pull/40007#issuecomment-578729356 and https://stackoverflow.com/questions/49907308/installing-xdebug-in-docker
      # If xdebug does not work, you may need to add an iptables rule to the INPUT chain: iptables -A INPUT -i br+ -j ACCEPT
      - host.docker.internal:host-gateway

  bf2sclone:
    build:
      dockerfile: Dockerfile.bf2sclone
      context: .
      target: dev
    volumes:
      - ./src/bf2sclone:/src/bf2sclone
      - bf2sclone-cache-volume:/src/bf2sclone/cache
    environment:
      # - XDEBUG_MODE=off   # Uncomment to disable xdebug
      # See ./src/bf2sclone/config.inc.php for all supported env vars
      - DBIP=db
      - DBNAME=bf2stats
      - DBLOGIN=admin
      - DBPASSWORD=admin
      # - TITLE=BF2S Clone
      - RANKING_REFRESH_TIME=0
      # - RANKING_HIDE_BOTS=false
      # - RANKING_HIDE_HIDDEN_PLAYERS=false
      # - LEADERBOARD_COUNT=25
    ports:
      - 8082:80
      - 9000
    networks:
      - traefik-network
      - bf2-network
    extra_hosts:
      # For xdebug to reach the host via `host.docker.internal`. See: https://github.com/moby/moby/pull/40007#issuecomment-578729356 and https://stackoverflow.com/questions/49907308/installing-xdebug-in-docker
      # If xdebug does not work, you may need to add an iptables rule to the INPUT chain: iptables -A INPUT -i br+ -j ACCEPT
      - host.docker.internal:host-gateway

  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=bf2stats
    volumes:
      - ./config/db/my.cnf:/etc/my.cnf:ro
      - db-volume:/var/lib/mysql
    networks:
      - bf2-network
    depends_on:
      - init-container

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=db
    ports:
      - 8083:80
    networks:
      - bf2-network

networks:
  gamespy-network:
  bf2-network:
  traefik-public-network:
  traefik-network:
    internal: true

volumes:
  prmasterserver-volume:
  backups-volume:
  config-volume:
  logs-volume:
  snapshots-volume:
  bf2sclone-cache-volume:
  db-volume:
