# This is a docker compose override file, for production builds with caching for CI environments
services:
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ../../src/python:/server/bf2/python # Mount the python files

  asp:
    build:
      dockerfile: Dockerfile.asp
      context: ../../
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-asp
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-asp,mode=max

  bf2sclone:
    build:
      dockerfile: Dockerfile.bf2sclone
      context: ../../
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-bf2sclone
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-bf2sclone,mode=max
